question_data = [
    {"text": "Python is a case sensitive language.",
     "answer": "True"},
    {"text": "Python is object-oriented language.",
     "answer": "True"},
    {"text": "Python is a scripting language.",
     "answer": "True"},
    {"text": "Python is a open source language.",
     "answer": "True"},
    {"text": "Python is a compiled language.",
     "answer": "False"},
    {"text": "Python is a cross platform language.",
     "answer": "True"},
    {"text": "Python runs on the chrome browser.",
     "answer": "False"},
    {"text": "Python is a high level language.",
     "answer": "True"},
    {"text": " Python is a hard to learn language.",
     "answer": "False"},
    {"text": "Python is a interpreted language.",
     "answer": "True"},
    {"text": "Python django library is used for game development.",
     "answer": "False"},
    {"text": "Python is a machine language.",
     "answer": "False"},
    {"text": "Python is developed by Guido van Rossum.",
     "answer": "True"},
    {"text": "Python is written in c language.",
     "answer": "True"},
    {"text": "Strings are immutable in Python, which means a string cannot be modified.",
     "answer": "True"},
    {"text": "Python does not support a character type; a single character is treated as strings of length one.",
     "answer": "True"},
    {"text": "In Python, list is mutable",
     "answer": "True"},
    {"text": "Items are accessed by their position in a dictionary ",
     "answer": "False"},
    {"text": "Dictionary keys must be immutable",
     "answer": "True"},
    {"text": "In Python, Dictionaries are immutable",
     "answer": "False"},
    {"text": "Python function always returns a value",
     "answer": "True"},
    {"text": "In Python3, Whatever you enter as input, the input() function converts it into a string",
     "answer": "True"},
]
